services:
  api_gateway:
    build: ./api_gateway
    volumes:
      - ./common:/app/common
    ports:
      - "5000:5000"
    depends_on:
      - service_auth
      - service_reports


  service_auth:
    build:
      context: ./service_auth
      dockerfile: Dockerfile
    volumes:
      - ./common:/app/common
      - ./dao:/app/dao
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: root
      MYSQL_PASSWORD: pw_123
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
    ports:
      - "5001:5001"
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  service_reports:
    build:
      context: ./service_reports
      dockerfile: Dockerfile
    volumes:
      - ./common:/app/common
    ports:
      - "5002:5002"


  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

#  mysql:
#    image: mysql:8.0
#    environment:
##      MYSQL_ROOT_PASSWORD: pw_123
#      MYSQL_DATABASE: demo_db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: pw_123
#    volumes:
#      - mysql_data:/var/lib/mysql
#    ports:
#      - "3306:3306"
