apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "chi-markets"
spec:
  configuration:
    zookeeper:
        nodes:
        - host: zookeeper.zoo1ns
          port: 2181
    clusters:
      - name: "cluster-the-one"
        layout:
          shardsCount: 2
          replicasCount: 2
        templates:
          podTemplate: clickhouse-stable
          volumeClaimTemplate: storage-vc-template
  templates:
    podTemplates:
      - name: clickhouse-stable
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:23.8.16.42.altinitystable
    volumeClaimTemplates:
      - name: storage-vc-template
        spec:
          storageClassName: sc-ebs
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
